### ISSUE TITLE
Add upgrade-insecure-requests to Header

### ISSUE THREAD

**Issue by fwebdev** [yandex/csp-tester#13]
At the Moment this rule is just removed. 

It would be nice to update the Extension according.

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests](url)

**Comment by oxdef** [comment]
Thanks for issue. upgrade-insecure-requests is not standard directive right now (see [CSP v2](https://www.w3.org/TR/CSP2/)). Need to think how to correctly add it into the CSP Tester...

**Comment by oxdef** [comment]
Fixed in Master branch. Will be in the nearest release.
